name: image-api-helper
version: 0.1.0.0
github: "nammayatri/nammayatri"
license: AllRightsReserved
author: "nammayatri"
maintainer: "nammayatri"
copyright: "2023 Juspay Technologies Private Limited"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/nammayatri/nammayatri#readme>

default-extensions:
  - DataKinds
  - KindSignatures
  - TypeOperators
  - DeriveGeneric
  - DeriveAnyClass
  - OverloadedStrings
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedStrings
  - PackageImports
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - BlockArguments
  - TypeSynonymInstances
  - UndecidableInstances
  - AllowAmbiguousTypes

dependencies:
  - base >= 4.7 && < 5
  - record-hasfield
  - record-dot-preprocessor
  - aeson
  - mobility-core
  - bytestring
  - clock
  - containers
  - openapi3
  - servant-server
  - text
  - time
  - wai
  - warp
  - servant-client
  - servant-client-core
  - unliftio
  - exceptions
  - http-client
  - case-insensitive
  - string-conversions
  - scientific
  - vector
  - extra
  - hedis
  - transformers
  - relude
  - record-hasfield
  - base64-bytestring

ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie
  - -Wall
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wunused-imports
  - -fplugin=RecordDotPreprocessor

library:
  source-dirs: src
  ghc-options:
    - -Wincomplete-uni-patterns
    - -Wwarn=ambiguous-fields

executables:
  image-api-helper-exe:
    main: Main.hs
    source-dirs: server
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N -T"'
      - -Wincomplete-uni-patterns
    dependencies:
      - image-api-helper
